services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gook_docker
      POSTGRES_PASSWORD: gookpass
      POSTGRES_DB: gook_docker
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
